/*/
File: QS_data_actions.sqf
Author:

	Quiksilver
	
Last modified:

	27/05/2019 A3 1.92 by Quiksilver
	
Description:

	Actions Text
___________________________________________/*/

[
	'Sit',
	'Сидiти',
	'Stand',
	'Стати',
	'Escort',
	'Супроводити',
	'Load',
	'Завантажити',
	'Load cargo',
	'Завантажити вантаж',
	'Unload',
	'Вивантажити',
	'Unload cargo',
	'Вивантажити вантаж',
	'Question civilian',
	'Опитати цивільного',
	'Drag',
	'Тягти',
	'Carry',
	'Нести',
	'Command Follow',
	'Слiдувати',
	'Command Recruit',
	'Вербувати',
	'Найняти',
	'Command Dismiss',
	'Команда Вiдпустити',
	'Command Surrender',
	'Капiтуляцiя',
	'Release',
	'Вiдчепити',
	'Вiдпустити',
	'Respawn vehicle',
	'Респаун транспорту',
	'Open cargo doors',
	'Вiдкрити дверi для вантажiв',
	'Close cargo doors',
	'Закрити дверi для вантажiв',
	'Service vehicle',
	'Обслуговування транспорту',
	'Service',
	'Обслуговування',
	'Clear vehicle inventory',
	'Очистити iнвентар транспорту',
	'Unflip',
	'Перекинути',
	'Перевернути',
	'Revive',
	'Оживити',
	(localize 'STR_A3_Arsenal'),
	'Beacons On',
	'Увiмкнути маячки',
	'Beacons Off',
	'Вимкнути маячки',
	'Tow',
	'Буксирувати',
	'Rescue',
	'Врятувати',
	'Secure',
	'Убезпечити',
	'Turret safety',
	'Безпека турелi',
	'Collect ear',
	'Забрати медальон',
	'Забрати вухо',
	'Collect gold tooth',
	'Забрати золотий зуб',
	'Turn on live feed',
	'Увiмкнути живу трансляцiю',
	'Увiмкнути трансляцiю наживо',
	'Turn off live feed',
	'Вимкнути живу трансляцiю',
	'Вимкнути трансляцiю наживо',
	'Activate air defense',
	'Активувати ППО',
	'Transport Leaderboard (Enable)',
	'Transport Leaderboard (Disable)',
	'Vote For Nighttime!',
	'Vote Against Nighttime!',
	'Unlock turret (Left)',
	'Розблокувати турелi (Лiва)',
	'Unlock turret (Right)',
	'Розблокувати турелi (Права)',
	'Lock turret (Left)',
	'Заблокувати турелi (Лiва)',
	'Lock turret (Right)',
	'Заблокувати турелi (Права)',
	'Cancel turret actions',
	'Вiдмiнити дiї за турелями',
	'Join group',
	'Приєднатись до групи',
	'FOB Status',
	'Статус FOB',
	'Статус ПОБ',
	'Activate FOB',
	'Активувати FOB',
	'Активувати ПОБ',
	'Enable FOB Respawn',
	'Активувати FOB респаун',
	'Активувати ПОБ респаун',
	'Cancel',
	'Вiдмiнити',
	'Unpack fortification',
	'Розпакувати укрiплення',
	'Pack fortification',
	'Запакувати укрiплення',
	'Edit Inventory',
	'Редагувати Інвентар',
	'Pick up intel',
	'Пiдняти данi',
	'Drop intel',
	'Кинути данi',
	'Upload intel',
	'Завантажити данi',
	'Activate device',
	'Активувати пристрiй',
	'About Us',
	'Push vehicle',
	'Штовхнути транспорт',
	'Перевернути транспорт',
	(localize 'STR_A3_BIS_fnc_initIntelObject_take'),
	'Take Intel',
	'Забрати даннi',
	'Inflate boat',
	'Suspend side missions',
	'Призупинити другоряднi мiсiї',
	'Resume side missions',
	'Продовжити другоряднi мiсiї',
	'Suspend primary missions',
	'Призупинити основнi мiсiї',
	'Resume primary missions',	
	'Продовжити основнi мiсiї',
	'Cycle primary mission',
	'Основну мiсiю в цикл',
	'0 - Close Menu',
	'1 - (Target) Delete',
	'2 - Spectate',			
	'3 - Invincibility',
	'4 - Show Pilots',
	'5 - (Target) Repair',
	'6 - (Target) Pardon',
	'7 - (Target) Punish',
	'8 - No function assigned',
	'9 - No function assigned',
	'10 - (Target) Revive',
	'11 - Map Teleport',
	'12 - (Clean) Base',
	'13 - (Clean) Island',
	'14 - Splendid Cam',
	'15 - Dev Terminal',
	'0 - Закрити меню',
	'1 - (Цiль) Видалити',
	'2 - Спостерiгати',
	'3 - Непереможнiсть',
	'4 - Показати пiлотiв',
	'5 - (Цiль) Вiдремонтувати',
	'6 - (Цiль) Вибачитись',
	'7 - (Цiль) Покарати',
	'10 - (Цiль) Оживити',
	'11 - Телепортацiя',
	'12 - (Очистити) Базу',
	'13 - (Очистити) Острiв',
	'Fastrope',
	'Швидкий спуск',
	'Fastrope AI units',
	'Detach fastrope',
	'Вiд’єднати мотузку',
	'Enable fastrope',
	'Увiмкнути швидкий спуск',
	'Disable fastrope',
	'Вимкнути швидкий спуск',
	'   ',
	'Pick up',
	'Пiдняти',
	'Download Locations',
	'Завантажити мiсцезнаходження',
	'Get Intel',
	'Отримати данi',
	'Treat at Medical Station',
	'Вилiкуватись в мед.пунктi',
	'Activate vehicle',
	'Активувати транспорт',
	'Weapons safe on base',
	'Зброя на запобiжнику',
	'Spawn plane',
	'Заспаунити лiтак',
	'Confirm target',
	'Підтвердити ціль',
	'Підтвердити ціль',
	'Пiдтвердити цiль',
	'Report target',
	'Повідомити про цiль',
	'Повiдомити про цiль',
	'Raise plow',
	'Підняти ковш',
	'Lower plow',
	'Опустити ковш',
	'Examine',
	'Розглянути',
	(localize 'STR_A3_action_useCatapult'),
	'Initiate Launch Sequence',
	'Розпочати запуск',
	'Launch',
	'Запуск',
	'Stabilise',
	'Стабiлiзувати',
	'Inspect',
	'Перевiрити',
	'Self destruct',
	'Самознищення',
	'Deploy camo net',
	'Розгорнути маскувальну сiтку',
	'Remove camo net',
	'Згорнути маскувальну сiтку',
	'Mount slat armor',
	'Встановити зовнiшню броню',
	'Remove slat armor',
	'Зняти зовнiшню броню',
	'Retract Cargo Ropes',
	'Втягнути вантажнi троси',
	'Extend Cargo Ropes',
	'Подовжити вантажнi троси',
	'Shorten Cargo Ropes',
	'Вкоротити вантажнi троси',
	'Release Cargo',
	'Вiдпустити вантажнi троси',
	'Deploy Cargo Ropes',
	'Випустити вантажнi троси',
	'Attach To Cargo Ropes',
	'Приєднати вантажнi троси',
	'Drop Cargo Ropes',
	'Скинути вантажнi троси',
	'Pickup Cargo Ropes',
	'Пiдняти вантажнi троси',
	'Покласти',
	'Положити',
	'Вiдмова',
	'Скасувати',
	'Транспортний сервiс',
	(if (isLocalized 'STR_A3_action_Recover_Boat') then {localize 'STR_A3_action_Recover_Boat'} else {'Вiдновити човен'}),
	'Role Selection',
	'Вибiр ролi'
]
